config/routes.rb
Rails.application.routes.draw do

  resources :subscriptions
  get 'charges/create'

  get 'client_portal/index'

  devise_for :clients
  root 'pages#main'

  resources :charges

  get '/contact_submission', to: 'pages#contact_submission', as: :contact_submission
  get '/email_submission', to: 'pages#email_submission', as: :email_submission

  # resources :client_portals

  get 'client-portal', to: 'companies#index', as: :client_portal

  resources :companies, except: :index

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :companies
  has_many :subscriptions
end

app/models/company.rb
class Company < ApplicationRecord

  belongs_to :client
  belongs_to :plan

  def add_card_info card_last4, card_exp_month, card_exp_year, card_type
    self.update(
      card_last4: card_last4,
      card_exp_month: card_exp_month,
      card_exp_year: card_exp_year,
      card_type: card_type
    )
    # self.card_last4 = card_last4
    # self.card_exp_month = card_exp_month
    # self.card_exp_year = card_exp_year
    # self.card_type = card_type
  end

  def add_stripe_sub_id stripe_subscription_id
    self.update(stripe_subscription_id: stripe_subscription_id)
  end

end

app/models/contact_submission.rb
class ContactSubmission < ApplicationRecord
end

app/models/email_submission.rb
class EmailSubmission < ApplicationRecord
end

app/models/plan.rb
class Plan < ApplicationRecord

  has_many :subscriptions
  has_many :companies
  
end

app/models/subscription.rb
class Subscription < ApplicationRecord

  belongs_to :clients
  belongs_to :plans
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  before_action :authenticate_client!
  before_action :set_client
  before_action :set_company

  def new
  end

  def create
    @client.stripe_id = params[:stripeToken]
    @company.add_card_info(
      params[:card_last4],
      params[:card_exp_month],
      params[:card_exp_year],
      params[:card_brand]
    )
    @company.add_stripe_sub_id(params[:stripe_subscription_id])
    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )
    # subscription = Stripe::Subscription.create(
    #   :customer => customer.id,
    #   :plan => @company.plan.stripe_id#{}"basic-monthly"#params[:plan]#"basic-annually",
    # )
    Stripe::Subscription.create(
      :customer => customer.id,
      :plan => @company.plan.stripe_id#{}"basic-monthly"#params[:plan]#"basic-annually",
    )
    flash[:notice] = "Thanks for your payment/subsription!"
    redirect_to client_portal_url
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to client_portal_path
  end

  private

  def set_client
    @client = current_client
  end

  def set_company
    @company = Company.find(params[:id])
  end
  
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  before_action :set_company, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_client!
  before_action :set_client

  def index
    @client_info = Client.includes(:companies).where(id: current_client.id)
  end

  def show
  end

  def new
    @company = Company.new
  end

  def edit
  end

  def create
    # plan = Plan.find_by(taco_id: params[:plan])
    # @company = Company.new(company_name: params[:company_name], domain: params[:domain], plan_id: plan.id)
    # @company.client_id = @client.id
    @company = Company.new(company_params)
    @company.client_id = @client.id
    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_company
    @company = Company.find(params[:id])
  end

  def company_params
    params.require(:company).permit(:company_name, :domain, :plan_id)
  end

  def set_client
    @client = current_client
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def main
  end

  def email_submission
    email = params[:email]
    EmailSubmission.create(email: email)
    flash[:notice] = "Thanks for inquiring! You should receive an email soon."
    redirect_to action: "main"
  end

  def contact_submission
    name = params[:name]
    email = params[:email]
    message = params[:message]
    ContactSubmission.create(name: name, email: email, message: message)
    flash[:notice] = "Thanks for reaching out! We will reply as soon as we can."
    redirect_to action: "main"
  end

end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController

  before_action :set_subscription, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_client!
  before_action :redirect_to_signup, only: [:new]

  # GET /subscriptions
  # GET /subscriptions.json
  def index
    @subscriptions = Subscription.all
  end

  # GET /subscriptions/1
  # GET /subscriptions/1.json
  def show
  end

  # GET /subscriptions/new
  def new
    @subscription = Subscription.new
  end

  # GET /subscriptions/1/edit
  def edit
  end

  # POST /subscriptions
  # POST /subscriptions.json
  def create
    @subscription = Subscription.new(subscription_params)

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to @subscription, notice: 'Subscription was successfully created.' }
        format.json { render :show, status: :created, location: @subscription }
      else
        format.html { render :new }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscriptions/1
  # PATCH/PUT /subscriptions/1.json
  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to @subscription, notice: 'Subscription was successfully updated.' }
        format.json { render :show, status: :ok, location: @subscription }
      else
        format.html { render :edit }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @subscription.destroy
    respond_to do |format|
      format.html { redirect_to subscriptions_url, notice: 'Subscription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

private

# Use callbacks to share common setup or constraints between actions.
def set_subscription
  @subscription = Subscription.find(params[:id])
end

# Never trust parameters from the scary internet, only allow the white list through.
def subscription_params
  # params.require(:subscription).permit(:clients_id, :plans_id)
end

def redirect_to_signup
  if !client_signed_in?
    session["client_return_to"] = new_subscription_path
    redirect_to new_client_registration_path
  end
end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def card_fields_class
    "hidden" if current_client.card_last4?
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/client_portal_helper.rb
module ClientPortalHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/charges/create.html.erb
<h1>Charges#create</h1>
<p>Find me in app/views/charges/create.html.erb</p>

app/views/client_portal/index.html.erb
<h1>ClientPortal#index</h1>
<p>Find me in app/views/client_portal/index.html.erb</p>

app/views/client_portals/index.html.erb
<div class="row">
  <% if flash[:notice] %>
    <div class="large-6 small-12 large-centered small-centered text-center">
      <p class="notice"><%= notice %></p>
    </div>
  <% end %>
  <% if flash[:alert] %>
    <div class="large-6 small-12 large-centered small-centered text-center">
      <p class="alert"><%= alert %></p>
    </div>
  <% end %>
  <h1>ClientPortal</h1>

  <%= link_to "Create A Company", new_company_path, class:"hollow button success large" %>

  <p>

    <% unless @client.client_portals.empty? %>
      <%= @client.client_portals.first.company_name %>
    <% end %>
  </p>

  <%= form_tag charges_path, id: "payment-form" do %>
    <input type="hidden" name="stripeToken" id="stripeToken" />
    <input type="hidden" name="card_last4" id="card_last4" />
    <input type="hidden" name="card_exp_month" id="card_exp_month" />
    <input type="hidden" name="card_exp_year" id="card_exp_year" />
    <input type="hidden" name="card_brand" id="card_brand" />
  <% end %>

  <!-- <%= link_to "Subscribe to a plan", subscriptions_path, class: "button success" %> -->
  <button class="hollow button large" id="stripe-demo">Subscribe</button>
  <script src="https://checkout.stripe.com/checkout.js"></script>
  <script>
    var paymentForm = document.getElementById('payment-form');
    var handler = StripeCheckout.configure({
      key: 'pk_test_Mz55NUk1Hbcdtv8xPH7edhvJ',
      image: 'http://heytaco-blog.s3.amazonaws.com/2016/09/golden-taco.jpg',
      locale: 'auto',
      token: function(token) {
        // You can access the token ID with `token.id`.
        // Get the token ID to your server-side code for use.
        console.log(token.id);
        console.log(token.card.last4);
        console.log(token.card.exp_month);
        console.log(token.card.exp_year);
        console.log(token.card.brand);

        document.getElementById('stripeToken').value = token.id;
        document.getElementById('card_last4').value = token.card.last4;
        document.getElementById('card_exp_month').value = token.card.exp_month;
        document.getElementById('card_exp_year').value = token.card.exp_year;
        document.getElementById('card_brand').value = token.card.brand;

        console.log("--------------")
        console.log(document.getElementById('stripeToken').value)
        console.log("--------------")

        // paymentForm.append(document.querySelector('<input type="hidden" name="stripeToken" />').val(token.id));
        // paymentForm.append(document.querySelector('<input type="hidden" name="card_last4" />').val(token.card.last4));
        // paymentForm.append(document.querySelector('<input type="hidden" name="card_exp_month" />').val(token.card.exp_month));
        // paymentForm.append(document.querySelector('<input type="hidden" name="card_exp_year" />').val(token.card.exp_year));
        // paymentForm.append(document.querySelector('<input type="hidden" name="card_brand" />').val(token.card.brand));
        // paymentForm.submit();
        document.getElementById("payment-form").submit();
      }
    });

    document.getElementById('stripe-demo').addEventListener('click', function(e) {
      // Open Checkout with further options:
      handler.open({
        amount: 2000,
        name: "Golden Taco Tech",
        description: "Pro Subscription ($29 per month)",
        panelLabel: "Subscribe",
        allowRememberMe: false
      });
      e.preventDefault();
    });

    // Close Checkout on page navigation:
    window.addEventListener('popstate', function() {
      handler.close();
    });
  </script>
</div>

app/views/companies/_form.html.erb
<%= form_with(model: company, local: true) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :company_name %>
    <%= form.text_field :company_name, id: :company_name %>
  </div>

  <div class="field">
    <%= form.label :domain %>
    <%= form.text_field :domain, id: :domain %>
  </div>

  <div class="field">
    <fieldset>
      <legend>Choose Your Plan</legend>
      <% if current_client.email == "rmrhomeservices@gmail.com" %>
        <%= form.radio_button :plan_id, 1, id: "rmr_home" %>
        <%= form.label :rmr_home_services, 'RMR Home Services Plan', for: 'rmr_home' %>
      <% elsif current_client.email == "spencer@tacoshirt.co" %>
        <%= form.radio_button :plan_id, 2, id: "test_plan" %>
        <%= form.label :rmr_home_services, 'Test Plan', for: 'test_plan' %>
      <% else %>
        <%= form.radio_button 'plan', 'basic-annually' %>
        <%= form.label :basic_annually, 'Basic Annually' %>
        <%= form.radio_button 'plan', 'basic-monthly' %>
        <%= form.label :basic_monthly, 'Basic Monthly' %>
      <% end %>
    </fieldset>
  </div>

  <div class="actions">
    <%= form.submit class: "button" %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<div class="row">
  <h1>Editing Company</h1>

  <%= render 'form', company: @company %>

  <%= link_to 'Show', @company %> |
  <%= link_to 'Back', company_path(@company) %>
</div>

app/views/companies/index.html.erb
<div class="row">
  <%= render 'layouts/flash' %>
  <h1>Companies</h1>

  <p>
    <% unless @client.companies.empty? %>
      <ul>
        <% @client.companies.each do |company| %>
          <li>
            <%= link_to company.company_name, company_path(company) %>
          </li>
        <% end %>
      </ul>
    <% end %>
  </p>

    <%= link_to "Create A Company", new_company_path, class:"hollow button success large" %>
</div>

app/views/companies/new.html.erb
<div class="row">
  <h1>New Company</h1>

  <%= render 'form', company: @company %>

  <%= link_to 'Show', @company %> |
  <%= link_to 'Back', client_portal_path %>
</div>

app/views/companies/show.html.erb
<div class="row">
  <%= render 'layouts/flash' %>
  <h1><%= @company.company_name %></h1>
  <h4>Domain: <%= @company.domain %></h4>
  <h4>Plan: <%= @company.plan.name %></h4>
  <%= form_tag charges_path(@company), id: "payment-form" do %>
    <input type="hidden" name="stripeToken" id="stripeToken" />
    <input type="hidden" name="card_last4" id="card_last4" />
    <input type="hidden" name="card_exp_month" id="card_exp_month" />
    <input type="hidden" name="card_exp_year" id="card_exp_year" />
    <input type="hidden" name="card_brand" id="card_brand" />
    <input type="hidden" name="id" id="id" />
  <% end %>

  <button class="hollow button success large" id="stripe-demo">Subscribe</button>
  <script src="https://checkout.stripe.com/checkout.js"></script>
  <script>
    var paymentForm = document.getElementById('payment-form');
    var handler = StripeCheckout.configure({
      key: '<%= ENV["stripe_publishable_key"] %>',
      image: 'http://heytaco-blog.s3.amazonaws.com/2016/09/golden-taco.jpg',
      locale: 'auto',
      token: function(token) {
        // You can access the token ID with `token.id`.
        // Get the token ID to your server-side code for use.
        document.getElementById('stripeToken').value = token.id;
        document.getElementById('card_last4').value = token.card.last4;
        document.getElementById('card_exp_month').value = token.card.exp_month;
        document.getElementById('card_exp_year').value = token.card.exp_year;
        document.getElementById('card_brand').value = token.card.brand;
        document.getElementById('id').value = '<%= @company.id %>';
        document.getElementById("payment-form").submit();
      }
    });

    document.getElementById('stripe-demo').addEventListener('click', function(e) {
      // Open Checkout with further options:
      handler.open({
        amount: '<%= @company.plan.price * 100 %>',
        name: "Golden Taco Consulting",
        description: '<%= @company.plan.name unless @company.plan.nil? %>',
        panelLabel: "Subscribe",
        allowRememberMe: false,
        email: '<%= @client.email %>'
        // plan: '<%= @company.plan.stripe_id %>'
      });
      e.preventDefault();
    });

    // Close Checkout on page navigation:
    window.addEventListener('popstate', function() {
      handler.close();
    });
  </script>
  <br />
  <%= link_to 'Back', client_portal_path, class: "hollow button" %>
  <%= link_to 'Edit', edit_company_path, class: "hollow button" %>
</div>

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
  <div class="large-6 small-12 large-centered small-centered text-center">
    <p class="notice"><%= notice %></p>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="large-6 small-12 large-centered small-centered text-center">
    <p class="alert"><%= alert %></p>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="responsive-blog-footer">
  <div class="row">
    <div class="medium-8 columns small-order-2 medium-order-1 about-container">
      <div class="row">
        <div class="hide-for-small-only medium-4 columns about-section">
          <%= image_tag('bearded-dude.png') %>
        </div>
        <div class="medium-8 columns about-section">
          <h4>Are you tired of having to DEAL WITH your current technology?</h4>
          <p>Let us help! We will create an amazing website, set up your email, and handle all things that you just don't have the time to mess with.</p> 
          <p>Need a custom application? No probelm! We can do it all.</p>
        </div>
      </div>
    </div>
    <div class="small-12 medium-4 columns small-order-1 medium-order-2 mailing-container" id="contact">
      <h4 class="mailing-list">Contact Us</h4>
      <%= form_tag(contact_submission_path, method: "get") do %>
        <div class="row">
          <%= label_tag 'name', 'Full Name *'%>
          <%= text_field_tag 'name', nil, placeholder: "Full Name" %>
        </div>
        <div class="row">
          <%= label_tag 'email', 'Email Address *'%>
          <%= email_field_tag 'email', nil, placeholder: "Email Address" %>
        </div>
        <div class="row">
          <%= label_tag 'message', 'Message *'%>
          <%= text_area_tag 'message', nil, rows: 5, placeholder: "Message" %>
        </div>
        <div class="contact-panel-actions">
          <%= submit_tag "Submit", class: "button expanded subscribe-button"%>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row tag-search">
    <div class="columns">
      <ul class="menu simple tag-section">
        <li><%= link_to "About Us", root_path(anchor: "about") %></li>
        <li><%= link_to "Info", root_path(anchor: "info") %></li>
        <li><a href="">Request Consultation</a></li>
      </ul>
    </div>
  </div>
  <div class="row columns flex-container align-justify">
     <p> all rights reserved</p>
    <div class="up-arrow">
      <a href="#top"><i class="fa fa-chevron-circle-up" aria-hidden="true"></i></a>
    </div>
  </div>
</footer>

app/views/layouts/_nav.html.erb
<nav class="top-bar topbar-responsive" id="top">
  <div class="top-bar-title">
    <span data-responsive-toggle="topbar-responsive" data-hide-for="medium">
      <button class="menu-icon" type="button" data-toggle></button>
    </span>
    <%= link_to "Golden Taco", root_path, class: "topbar-responsive-logo" %>
  </div>
  <div id="topbar-responsive" class="topbar-responsive-links">
    <div class="top-bar-right">
      <ul class="menu simple vertical medium-horizontal">
        <li><a href="#">Home</a></li>
        <li><%= link_to "About Us", root_path(anchor: "about") %></li>
        <li><%= link_to "Info", root_path(anchor: "info") %></li>
        <li><%= link_to "Contact", root_path(anchor: "contact") %></li>
        <li><%= link_to "Client Portal", client_portal_path %></li>
        <% if client_signed_in? %>
          <li><%= link_to "Sign Out", destroy_client_session_path, method: :delete %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Taco Consulting" %></title>
    <%= favicon_link_tag 'cropped-favicon.png' %>
    <link href="https://fonts.googleapis.com/css?family=Bungee+Outline|Cabin" rel="stylesheet">
    <%= stylesheet_link_tag    "application", media: 'all' %>
    <%= javascript_include_tag 'https://js.stripe.com/v2/', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <%= yield %>

    <%= render 'layouts/footer' %>

    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
  </body>
</html>

app/views/pages/_about.html.erb
<!-- <section class="four-up-feature">
  <div class="row four-up-feature-header align-center">
    <div class="medium-12 columns">
      <h2>The Menu</h2>
      <h5>Take a look at all the options you can order. Click a package to see more.</h5>
    </div>
  </div>
  <div class="row align-spaced">
    <div class="small-10 medium-3 columns">
      <img class="four-up-feature-image" src="http://placehold.it/75" alt="icon">
      <h4>Basic Package</h4>
      <div class="four-up-feature-text">
        <ul>
          <li>Landing page</li>
          <li>About us</li>
          <li>Contact form</li>
          <li>Domain setup</li>
          <li>Admin panel</li>
          <li>Social media links</li>
          <li>+$29 monthly hosting & maintenance</li>
        </ul>
      </div>
    </div>
    <div class="small-10 medium-3 columns">
      <div>Most Popular</div>
      <img class="four-up-feature-image" src="http://placehold.it/75" alt="icon">
      <h4>Premium Package</h4>
      <div class="four-up-feature-text">
        <ul>
          <li>Landing page</li>
          <li>About us</li>
          <li>Contact form</li>
          <li>Domain setup</li>
          <li>Admin panel</li>
          <li>Social media links</li>
          <li>Gallery page for images</li>
          <li>+$49 monthly hosting & maintenance</li>
        </ul>
      </div>
    </div>
    <div class="small-10 medium-3 columns">
      <img class="four-up-feature-image" src="http://placehold.it/75" alt="icon">
      <h4>The Whole Enchilada</h4>
      <p class="four-up-feature-text">
        Do you need someone to handle your site from top to bottom? From site creation, design, build, and management. We will take care of the whole enchilada! Enter your email to get started.
      </p>
    </div>
  </div>
</section> -->

<section>
  <div class="medium-12 columns" align="center" style="padding-bottom:2em;">
    <h2>The Menu</h2>
    <h5>Order the plate thats right for you and your company</h5>
  </div>
</div>
  <div style="align:center">
    <table style="width:50%;" align="center">
    <tr>
      <th></th>
      <th>Basic $799</th>
      <th>Premium $1199</th>
      <th>Whole Enchilada</th>
    </tr>
    <tr>
      <td>Landing page</td>
      <td><span class="badge success"><i class="fi-check"></i></span></td>
      <td><span class="badge success"><i class="fi-check"></i></span></td>
      <td><span class="badge success"><i class="fi-check"></i></span></td>
    </tr>
    <tr>
      <td>About Us Page</td>
      <td><span class="badge success"><i class="fi-check"></i></span></td>
      <td><span class="badge success"><i class="fi-check"></i></span></td>
      <td><span class="badge success"><i class="fi-check"></i></span></td>
    </tr>
    <tr>
      <td>Contact Form</td>
      <td><span class="badge success"><i class="fi-check"></i></span></td>
      <td><span class="badge success"><i class="fi-check"></i></span></td>
      <td><span class="badge success"><i class="fi-check"></i></span></td>
    </tr>
    <tr>
      <td>Domain Setup</td>
      <td><span class="badge success"><i class="fi-check"></i></span></td>
      <td><span class="badge success"><i class="fi-check"></i></span></td>
      <td><span class="badge success"><i class="fi-check"></i></span></td>
    </tr>
    <tr>
      <td>Admin Panel</td>
      <td><span class="badge success"><i class="fi-check"></i></span></td>
      <td><span class="badge success"><i class="fi-check"></i></span></td>
      <td><span class="badge success"><i class="fi-check"></i></span></td>
    </tr>
    <tr>
      <td>Social Media Links</td>
      <td><span class="badge success"><i class="fi-check"></i></span></td>
      <td><span class="badge success"><i class="fi-check"></i></span></td>
      <td><span class="badge success"><i class="fi-check"></i></span></td>
    </tr>
    <tr>
      <td>Custom Gallery Pages</td>
      <td></td>
      <td><span class="badge success"><i class="fi-check"></i></span></td>
      <td><span class="badge success"><i class="fi-check"></i></span></td>
    </tr>
    <tr>
      <td>Custom Site Design</td>
      <td></td>
      <td></td>
      <td><span class="badge success"><i class="fi-check"></i></span></td>
    </tr>
    <tr>
      <td>Database Management</td>
      <td></td>
      <td></td>
      <td><span class="badge success"><i class="fi-check"></i></span></td>
    </tr>
    <tr>
      <td>Monthly Hosting Fee</td>
      <td>$29</td>
      <td>$49</td>
    </tr>
    <tr>
      <td></td>
      <td>Select</td>
      <td>Select</td>
      <td>Select</td>
    </tr>
  </table>
</div>
</section>

app/views/pages/main.html.erb
<div class="top-section">
  <%= render 'layouts/flash' %>
  <div class="row">
    <div class="large-12 columns text-center">
      <h2 class="main-title">Golden Taco</h2>
      <h4 class="secondary-title">Consulting</h4>
    </div>
  </div>
  <div class="row">
    <div class="large-4 small-10 small-centered">
      <p class="text-center email-text">
        Interested in making life just a little bit easier?
        <br>
        Enter your email to find out how.
      </p>
      <div class="email-form">
        <%= form_tag(email_submission_path, method: "get") do %>
          <div class="input-group">
            <%= email_field_tag 'email', nil, placeholder: "Email Address", class: "input-group-field" %>
            <div class="input-group-button">
              <%= submit_tag "Submit", class: "button"%>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div id="info">
  <%= render 'info' %>
</div>

<div id="about">
  <%= render 'about' %>
</div>

app/views/subscriptions/edit.html.erb
<h1>Editing Subscription</h1>

<%= render 'form', subscription: @subscription %>

<%= link_to 'Show', @subscription %> |
<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/new.html.erb
<div class="row">
  <h1>New Subscription</h1>

  <h1>Subscribe!</h1>

  <button class="button success" id="stripe-demo">Subscribe</button>

  <script src="https://checkout.stripe.com/checkout.js"></script>
  <script>
    var handler = StripeCheckout.configure({
      key: "pk_test_1MCYLYHQDa4DwnBoKd5CqoaP",
      image: "https://stripe.com/img/documentation/checkout/marketplace.png",
      name: "Demo SaaS Site",
      description: "Subscription ($29 per month)",
      panelLabel: "Subscribe",
      allowRememberMe: false
    });

    document.getElementById('stripe-demo').addEventListener('click', function(e) {
      handler.open();
      e.preventDefault();
    });
  </script>

  <%= link_to 'Back', subscriptions_path %>
</div>

app/views/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Clients:</strong>
  <%= @subscription.clients %>
</p>

<p>
  <strong>Plans:</strong>
  <%= @subscription.plans %>
</p>

<%= link_to 'Edit', edit_subscription_path(@subscription) %> |
<%= link_to 'Back', subscriptions_path %>